services:
    genj_sso_client.broker:
        class: Genj\SsoClientBundle\Sso\Broker
        scope: request
        arguments:
            - @request
            - %genj_sso_client%

    genj_sso_client.action_listener:
        class: Genj\SsoClientBundle\EventListener\AuthenticationListener
        arguments: [@genj_sso_client.broker]
        scope: request
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }